version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/.venv
    env_file:
      - dev.env
    ports:
      - "9001:9001"
    entrypoint: "sh"
